# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_method_doc_test',
                'doc_host': 'https://lukastk.github.io',
                'git_url': 'https://github.com/lukastk/nbdev_method_doc_test',
                'lib_path': 'nbdev_method_doc_test'},
  'syms': { 'nbdev_method_doc_test.core': { 'nbdev_method_doc_test.core.foo1': ('core.html#foo1', 'nbdev_method_doc_test/core.py'),
                                            'nbdev_method_doc_test.core.foo2': ('core.html#foo2', 'nbdev_method_doc_test/core.py')}}}
