# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo1', 'foo2']

# %% ../nbs/00_core.ipynb 4
def foo1(
        ) -> int: # Return type documentation
    """Docstring"""
    return 1

# %% ../nbs/00_core.ipynb 5
def foo2(
        a, # test
        ) -> int: # Return type documentation
    """Docstring"""
    return 1
